Changes menu entry.
nextcloud/text pull request #2292
Opened 2022-04-12 15:59 UTC by pierreozoux

We realized with our users that when the apps Text and ONLYOFFICE are installed in parallel, this is a bit confusing.

You can see a screenshot here, in french:
https://forge.liiib.re/indiehost/tech/plateforme/-/issues/217#note_9733

So we propose this change.

In relation to this change in [onlyoffice app](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/617).

2022-04-13 06:34 UTC, max-nextcloud commented
Hi @pierreozoux 

Thanks a lot for your proposal. I'm a bit unsure about using 'Note' instead as there is a Notes app - so this might be confusing if you create a note somewhere and then it does not show in the notes app (because that app only works on one folder).

I agree that `New text document` is confusing. For me it's mostly the document part. That sounds like something formal on a page with layout and all that.

My personal preference would be just `New text` - do you think that would make it easier to distinguish?

I'd be really curious what @jancborchardt and @nimishavijay think.

2022-04-13 07:40 UTC, pierreozoux commented
@imacrea what do you think?

2022-04-15 09:33 UTC, ImaCrea commented
> @ImaCrea what do you think?

What about `New pad` @max-nextcloud ?

2022-04-19 07:28 UTC, juliushaertl commented
The text app is advertised and documented as a text editor so from my perspective either "New text document" or "New text file" are the most fitting terms. Pad is not really a term that is understandable for non-technical users from my perspective and note is something that may add a wrong connection to the notes app, but I would appreciate feedback from @jancborchardt and @nimishavijay here as well :)

2022-04-19 09:48 UTC, ImaCrea commented
> The text app is advertised and documented as a text editor so from my perspective either "New text document" or "New text file" are the most fitting terms. Pad is not really a term that is understandable for non-technical users from my perspective and note is something that may add a wrong connection to the notes app, but I would appreciate feedback from @jancborchardt and @nimishavijay here as well :)

Understood. `New text file` sounds good to me then. It's the 'document' part of the current wording that can be misleading when office suite like collabora or onlyoffice are integrated.

2022-04-19 09:51 UTC, nimishavijay commented
I can understand how it could be confusing when there is a "New document" right underneath. 
"New text" seems a bit incomplete, and "New pad" won't be understood by many as I've seen it being used only with EtherPad, so I would vote for "New text file" :)

2022-04-19 10:02 UTC, jancborchardt commented
Yep, agree with the points made by @max-nextcloud @juliushaertl and @nimishavijay. Let’s go for "New text file". :)

2022-04-19 13:14 UTC, juliushaertl requested changes
See inline comment for the wording as per discssion, in addition the wording in https://github.com/nextcloud/text/blob/551729e08d7c044ae34d8972129caa448725f7a9/lib/AppInfo/Application.php#L71 will also need to be adjusted.

2022-04-19 13:14 UTC, juliushaertl commented on src/helpers/files.js
> +				templateName: t('text', 'New note') + '.md',
```suggestion
				displayName: t('text', 'New text file'),
				templateName: t('text', 'New text file') + '.md',
```

2022-04-25 12:28 UTC, juliushaertl commented
Looks good for the frontend part, could you also adjust that accordingly in https://github.com/nextcloud/text/blob/551729e08d7c044ae34d8972129caa448725f7a9/lib/AppInfo/Application.php#L71 ?

2022-04-26 13:34 UTC, pierreozoux commented
@juliushaertl I think I did all the changes, looks goot to :ship: to me :)

2022-04-27 11:15 UTC, max-nextcloud commented
/rebase

2022-04-27 11:24 UTC, max-nextcloud commented
I rebased on top of the current master and rebuild the js. Hope that tests pass now and we can merge after.
Thanks a lot for your contribution @pierreozoux

2022-04-27 11:44 UTC, max-nextcloud commented
cypress failure is not related.Will look into that separately.

2022-04-27 11:44 UTC, merged

2022-05-20 09:59 UTC, pierreozoux commented
@max-nextcloud do you think it is possible to backport this little change? Or is it a "big" change, and will have to wait 25th?

2022-05-20 11:36 UTC, max-nextcloud commented
I'd be okay with backporting this - I'll open a backport pr to have the discussion there.

2022-05-20 11:37 UTC, max-nextcloud commented
/backport to stable24

2022-05-20 12:22 UTC, pierreozoux commented
/backport to stable23