🩹 (#2463): show a fallback image when image can't be loaded
nextcloud/text pull request #2466
Opened 2022-06-01 16:44 UTC by vinicius73

* Resolves: #2463
* Target version: master 

### Summary

Display a fallback image when image loading fails.

![image](https://user-images.githubusercontent.com/1561347/172721570-6fe930a5-a14e-4553-9cea-f47d0ebe3f0b.png)

2022-06-02 08:24 UTC, jancborchardt commented
@vinicius73 some design feedback:
- The icon can be the general image icon, does not need to be a specific "broken" one: https://fonts.google.com/icons?selected=Material%20Icons%3Aimage%3A
- Color should be grey, also for the text, color-text-maxcontrast. It’s not a "red error" type big deal. :)
- The message "Failed to load image" can show below together with the filename, as to not introduce another text block above. Just: "Failed to load [filename]" like "Failed to load image2.jpg"
- The initial `/` should be removed, it’s too technical

2022-06-02 08:25 UTC, jancborchardt requested changes
@vinicius73 some design feedback:
- [x] The icon can be the general image icon, does not need to be a specific "broken" one: https://fonts.google.com/icons?selected=Material%20Icons%3Aimage%3A
- [x] Color should be grey, also for the text, color-text-maxcontrast. It’s not a "red error" type big deal. :)
- [x] The message "Failed to load image" can show below together with the filename, as to not introduce another text block above. Just: "Failed to load [filename]" like "Failed to load image2.jpg"
- [ ] The initial `/` should be removed, it’s too technical

2022-06-02 13:27 UTC, vinicius73 commented
> The initial / should be removed, it’s too technical

It's the description of the image, I've put it as an example.

2022-06-03 15:16 UTC, eneiluj reviewed
I agree with @jancborchardt comments.

Code-wise, nothing to add. I guess the `ErrorLoadImage` is part of the solution we figured out with @mejo- about knowing when all images are loaded in Collectives, right?

The error could be renamed to `LoadImageError` but that's nitpicking :grin:.

2022-06-06 20:35 UTC, vinicius73 commented
@jancborchardt what is the best alternative?

Original/raw src parameter. (for now I am using this)
![image](https://user-images.githubusercontent.com/1561347/172241379-f2ad40eb-b7b4-48de-bdd0-0616cda3dc22.png)

With full URL used to load image (parsed by ImageView component)
![image](https://user-images.githubusercontent.com/1561347/172241608-b7c5ea4d-d318-4000-b17e-9597abd33904.png)

2022-06-06 20:35 UTC, vinicius73 commented
/compile

2022-06-06 21:17 UTC, mejo- commented
> @jancborchardt what is the best alternative?
> 
> Original/raw src parameter. (for now I am using this) ![image](https://user-images.githubusercontent.com/1561347/172241379-f2ad40eb-b7b4-48de-bdd0-0616cda3dc22.png)

I would vouch for `Failed to load invalid.png`, without square brackets and without any path elements - just the basename of the image. That's the least technical and easiest to understand for users in my opinion.

2022-06-06 21:22 UTC, mejo- reviewed
Thanks a lot for implementing this, @vinicius73 <3

2022-06-06 21:22 UTC, mejo- commented on src/components/icons.js
> +import MDI_ImageBroken from 'vue-material-design-icons/ImageBrokenVariant'
This can probably be removed now that you use `ImageOutline`, right?

2022-06-06 21:22 UTC, mejo- commented on src/components/icons.js
> +export const ImageBroken = makeIcon(MDI_ImageBroken)
Same here :relaxed:

2022-06-08 19:27 UTC, vinicius73 commented
/compile

2022-06-08 21:55 UTC, vinicius73 commented
/compile amend

2022-06-08 22:24 UTC, vinicius73 commented
@juliushaertl I've reverted this commit: a70841ac98cdfdbd376f2406eebd3ce30ce5fc32

It was generating error 500 from API.

```
POST /index.php/apps/text/session/fetch HTTP/1.1" 500
````

2022-06-09 08:36 UTC, juliushaertl commented
Rebased to retrigger tests after #2495 was merged

2022-06-09 09:05 UTC, juliushaertl approved these changes

2022-06-09 09:05 UTC, juliushaertl commented
/compile

2022-06-09 09:29 UTC, merged