fix: mention search issues
nextcloud/text pull request #3068
Opened 2022-09-28 16:53 UTC by luka-nextcloud

Signed-off-by: Luka Trovic <luka@nextcloud.com>

* Resolves: #2905
* Target version: master 

### Summary

2022-09-29 10:59 UTC, vinicius73 commented
LGTM;

Is it possible to have tests for it?

2022-09-29 17:37 UTC, mejo- reviewed
Thanks for looking into it @luka-nextcloud! I agree with @vinicius73 that we should have tests for that.

2022-09-29 17:37 UTC, mejo- commented on lib/Controller/UserApiController.php
> +use Psr\Log\LoggerInterface;
Looks like a leftover to me :)

2022-10-04 12:07 UTC, mejo- commented on lib/Controller/UserApiController.php
> +use Psr\Log\LoggerInterface;
Did you see this comment @luka-nextcloud?

2022-10-04 12:20 UTC, mejo- commented
/backport to stable25

2022-10-04 12:22 UTC, mejo- commented on lib/Controller/UserApiController.php
> +use Psr\Log\LoggerInterface;
Sorry, just realized that you fixed it in a follow-up commit.

2022-10-04 12:23 UTC, mejo- approved these changes
Thanks a lot @luka-nextcloud, works as expected now :heart:

2022-10-04 12:27 UTC, mejo- requested changes

2022-10-04 12:27 UTC, mejo- commented on tests/unit/Controller/UserApiControllerTest.php
> +			$this->assertInstanceOf(DataResponse::class, $users);
Well, this test only tests if `$users` is a `DataResponse` object, right? It seems to miss the actual tests on the content of the response? :thinking:

2022-10-04 12:30 UTC, mejo- commented
@luka-nextcloud also, please fix the code style issues reported by php-cs-fixer (see PHP linting CI job).

2022-10-05 19:07 UTC, luka-nextcloud commented
@mejo- Please check again :)

2022-10-10 14:18 UTC, mejo- commented on lib/Controller/UserApiController.php
> -			$user = $this->userSession->getUser();
Since you no longer use `userSession`, could you also remove it from the constructor @luka-nextcloud?

2022-10-10 14:47 UTC, mejo- commented on tests/unit/Controller/UserApiControllerTest.php
> +			$this->assertInstanceOf(DataResponse::class, $users);
Fixed myself now :)

2022-10-10 16:17 UTC, mejo- approved these changes

2022-10-10 17:40 UTC, merged