bugfix/noid/workspace filelists
nextcloud/text pull request #3349
Opened 2022-11-02 12:44 UTC by juliushaertl

- Do not render the workspace if file list is hidden
- Add cypress tests for switching views with rich workspaces

* Resolves: # 
* Target version: master 

### Summary

2022-11-02 12:47 UTC, juliushaertl commented
The event itself is available since 24 by the backports of https://github.com/nextcloud/server/pull/34100

2022-11-02 12:54 UTC, mejo- reviewed
The fix works well when tested locally. Cypress tests seem to need some love though.

2022-11-02 13:12 UTC, juliushaertl commented
Strange, it was passing fine locally, but I'll dive into that.

2022-11-07 14:10 UTC, max-nextcloud requested changes
Code looks good.

Requesting some minor changes that will make retries use consistent folder names.

2022-11-07 14:13 UTC, max-nextcloud commented on cypress/e2e/workspace.spec.js
> +			.get('.ProseMirror')
The first get already fails. So i guess you want this:
```suggestion
		cy.get('#rich-workspace .ProseMirror')
```

2022-11-07 14:14 UTC, max-nextcloud commented on cypress/e2e/workspace.spec.js
> +			.should('not.exist')
`#rich-workspace` does not exist at all in this scenario. So the first get fails.
```suggestion
		cy.get('#rich-workspace .ProseMirror')
			.should('not.exist')
```

2022-11-07 14:21 UTC, max-nextcloud approved these changes

2022-11-07 15:06 UTC, mejo- approved these changes
Thanks for fixing the tests @max-nextcloud.

2022-11-07 15:06 UTC, mejo- commented
/compile

2022-11-07 15:19 UTC, mejo- commented
/backport 581233665bb7516c2da5cd3bd74f030c08ff10f2,f85a3cd5c996dbfe8d2230859d67ae5c17847242,9fed8ea72469d6d25c6723689aa5c2b634ea1a52 to stable25

2022-11-07 16:14 UTC, juliushaertl commented
Failures/flaky tests are known, merging

2022-11-07 16:14 UTC, merged

2022-11-07 16:17 UTC, mejo- commented
/backport 581233665bb7516c2da5cd3bd74f030c08ff10f2,f85a3cd5c996dbfe8d2230859d67ae5c17847242,9fed8ea72469d6d25c6723689aa5c2b634ea1a52 to stable24