fix: solve publicly shared document with hide download issue
nextcloud/text pull request #3765
Opened 2023-02-06 07:19 UTC by luka-nextcloud

Signed-off-by: Luka Trovic <luka@nextcloud.com>

### 📝 Summary

* Resolves: #3704

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

2023-02-06 08:56 UTC, juliushaertl commented
Tests need adjustment

2023-02-08 11:15 UTC, juliushaertl commented
/backport to stable25

2023-02-09 15:51 UTC, luka-nextcloud commented on cypress/e2e/share.spec.js
> -	it('Share a file with download disabled shows an error', function() {
I have a concern. I set the download attribute to false for a share but the download button still appears. Is there any additional thing I need to do?

2023-02-15 13:44 UTC, juliushaertl commented on cypress/e2e/share.spec.js
> -	it('Share a file with download disabled shows an error', function() {
Let's not remove this test.

For clarity. There are two separate features:
- Disable download (on internal shares only) which will block the download of the file -> For this we need to show the error message that this cypress test checks for
- Hide download (only on share links) which does not block and just hides any visible download options -> Which the change in DocumentService of this PR brings back to work.

2023-02-15 13:45 UTC, juliushaertl commented on cypress/e2e/share.spec.js
> -	it('Share a file with download disabled shows an error', function() {
Cypress still pass fine with the change locally, but are a bit flaky due to other reasons.

2023-02-22 12:00 UTC, juliushaertl requested changes

2023-02-28 10:16 UTC, max-nextcloud commented on cypress/e2e/share.spec.js
> -		cy.shareFileToUser('test.md', recipient, {
@luka-nextcloud this is still missing. Just a matter of reverting the file to the state in main.

2023-02-28 14:38 UTC, luka-nextcloud commented
@max-nextcloud @juliushaertl It's all done now. :)

2023-02-28 14:57 UTC, juliushaertl approved these changes

2023-02-28 16:19 UTC, merged