fix: split layout of conflict view
nextcloud/text pull request #3951
Opened 2023-03-16 11:22 UTC by max-nextcloud

### 📝 Summary

Give both versions 50% of the screen space and try to vertically align them. This should make comparing the versions easier.

Fixes #3950.

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
![Open test md in viewer -- displays conflicts](https://user-images.githubusercontent.com/97337118/225600918-118cd401-2c7c-4852-bf23-462411e0ddd9.png)
 | 
![Open test md in viewer -- displays conflicts (2)](https://user-images.githubusercontent.com/97337118/225600971-d767b454-3945-4467-8cb3-cd19e8a5b201.png)

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation is not required

2023-03-16 11:26 UTC, mejo- commented on cypress/e2e/sync.spec.js
> +	it.only('reconnect does not lead to an empty file', () => {
Is `it.only` wanted here? Seems like a developing leftover :thinking:

2023-03-16 11:28 UTC, mejo- requested changes

2023-03-16 11:28 UTC, mejo- commented on cypress/e2e/sync.spec.js
Are changes to this file even meant to be part of the PR? They seem legit but unrelated :wink:

2023-03-16 11:40 UTC, max-nextcloud commented on cypress/e2e/sync.spec.js
I was so sure i did not git commit -a ... but there it is.

2023-03-16 12:09 UTC, mejo- approved these changes

2023-03-16 13:03 UTC, max-nextcloud commented
/backport to stable26

2023-03-16 21:12 UTC, mejo- commented
/compile

2023-03-17 08:05 UTC, merged

2023-03-17 08:10 UTC, mejo- commented
/backport e83f2db0c35620b3174b929660d75686871c6f0d,21d48ec36dd49c63aaa7185e443b9d3043cffe60 to stable26