fix: scroll for outline
nextcloud/text pull request #3999
Opened 2023-03-27 13:49 UTC by luka-nextcloud

### 📝 Summary

* Resolves: #3585

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
![image](https://user-images.githubusercontent.com/89908051/227958474-99fcbee7-b8e1-4f79-bc9b-c352a478180e.png) | [outline-scroll.webm](https://user-images.githubusercontent.com/89908051/228292210-7386a3fd-5ac7-414b-b56e-a8b555363dbe.webm)

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

2023-03-27 18:42 UTC, mejo- requested changes

2023-03-27 18:42 UTC, mejo- commented on src/components/Editor/TableOfContents.vue
> +	overflow-x: hidden;
Mh, does this work with long headings? What I meant is that the scrollbar should not be there if it is not needed for viewing the whole heading, but for sure it should be there once the heading is too long for being displayed completely within the container without scrolling.

2023-03-27 18:46 UTC, mejo- commented on src/components/Editor/TableOfContents.vue
> +	max-height: 73vh;
I also cannot think of a solution that doesn't involve a fixed (relative) height. Without a fixed height, the container will just grow as much as needed to list all headings. But `73vh` already is relative to the window height, so I think it should be ok. Do you have another idea how to tackle this, @juliushaertl?

2023-03-28 08:22 UTC, juliushaertl commented on src/components/Editor/TableOfContents.vue
> +	max-height: 73vh;
I think I would rather make the `.editor-outline` scrollable (which it should be already it seems) and limit its height to `calc(100% - 90px)`. Note 90px is just a dummy value as it seems that the outline is also positioned a bit wrongly in terms of the top offset on master.

2023-03-28 15:46 UTC, luka-nextcloud commented
@juliushaertl @mejo- Please check again.

2023-03-28 15:52 UTC, mejo- commented on src/components/Editor/EditorOutline.vue
> +	height: calc(100% - 100px);
This probably still should be `max-height`, to not let the container grow unnecessarily for very short outlines?

2023-03-29 12:12 UTC, mejo- commented
Please note that one problem remains even with my changes: the `max-height` of the outline container is not really dynamic. If Text gets used somewhere with even more vertical offset to the window top, it might not work. But the only other option I see is to set `max-height` dynamically using Javascript by calculating the vertical offset. Maybe @juliushaertl or @max-nextcloud have a better idea?

2023-04-12 11:39 UTC, mejo- commented
After discussing this again with @juliushaertl, we agreed to merge the PR as it is for now. At least it fixes the issue for Text in Viewer, standalone and in Collectives.

2023-04-12 11:39 UTC, mejo- approved these changes
@luka-nextcloud I took the liberty to rebase and squash the commits.

2023-04-12 12:18 UTC, mejo- commented
/compile

2023-04-12 12:43 UTC, merged

2023-04-12 12:43 UTC, mejo- commented
/backport b741f9237e4b5b1335fd02d33b333e366703e57e to stable26

2023-04-12 12:43 UTC, mejo- commented
/backport b741f9237e4b5b1335fd02d33b333e366703e57e to stable25

2023-04-12 12:59 UTC, mejo- commented
/backport /b741f9237e4b5b1335fd02d33b333e366703e57e,e5f57db008e73f40a7b00db5ff57bf2dcc7753cc to stable26