fix: Call to a member function getUserId() on bool
nextcloud/text pull request #4170
Opened 2023-05-11 11:13 UTC by solracsf

### 📝 Summary

Check that `$currentSession` is not false before trying to retrieve the user.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

2023-05-15 07:01 UTC, juliushaertl commented on lib/Controller/SessionController.php
> +			if ($userId !== false) {
Do you have an exception trace or error log of this being an issue?

2023-05-23 12:29 UTC, max-nextcloud commented on lib/Controller/SessionController.php
> +			if ($userId !== false) {
Looks like the issue in this trace was fixed in https://github.com/nextcloud/text/commit/6640ad287a6636ec14b517a5b6b01e97883ef88a

could you try upgrading to Nextcloud 25 and see if that fixes it?

2023-05-23 13:24 UTC, max-nextcloud requested changes
It's not clear to me if this actually fixes an issue.

Could you check and clarify if it still does?

2023-06-07 20:55 UTC, juliushaertl commented
Let's close this for now.

@solracsf Feel free to reopen and adjust if there is a related fix for the main branch still needed.

2023-06-07 20:55 UTC, closed without merging