ci(cypress): Use cypress-split for running tests in parallel
nextcloud/text pull request #4847
Opened 2023-10-11 18:14 UTC by juliushaertl

Signed-off-by: Julius Härtl <jus@bitgrid.net>

### 📝 Summary

* Resolves: # 

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

2023-10-11 18:42 UTC, juliushaertl commented
Job summary is not optimal likely due to our custom specPattern config (ref https://github.com/bahmutov/cypress-split/issues/69)

2023-10-11 19:46 UTC, mejo- requested changes

2023-10-11 19:46 UTC, mejo- commented on .github/workflows/cypress.yml
> -        run-in-parallel:
`run-in-parallel` is used further down in the workflow, so I think it's worth keeping it for now. Maybe we can change this to `${{ !!github.head_ref }}` again, to make sure that CI runs on development+release branches don't register in the Cypress cloud - and only the PR CI jobs end up in Cypress cloud.

2023-10-12 06:00 UTC, skjnldsv commented on cypress.config.js
> +})
```suggestion
const cypressSplit = require('cypress-split')

module.exports = defineConfig({
	e2e: {
		setupNodeEvents(on, config) {
			// IMPORTANT: return the config object
			return config
		},
	},
})
```

2023-10-12 06:01 UTC, skjnldsv commented on cypress.config.js
> +})
```suggestion
const cypressSplit = require('cypress-split')

module.exports = defineConfig({
	e2e: {
		setupNodeEvents(on, config) {
			// IMPORTANT: return the config object
			return config
		},
	},
})
```

2023-10-12 06:02 UTC, skjnldsv commented on cypress.config.js
> +})
```suggestion
const cypressSplit = require('cypress-split')

module.exports = defineConfig({
	e2e: {
		setupNodeEvents(on, config) {
			// IMPORTANT: return the config object
			return config
		},
	},
})
```

2023-10-12 16:43 UTC, juliushaertl commented
Good to go from my side.

The author has also already [fixed the github summary for our case](https://github.com/bahmutov/cypress-split/pull/118) already which now nicely displays spec stats:

https://github.com/bahmutov/cypress-split/actions/runs/6496437037#summary-17643354799

One more report remaining about the time but that doesn't seem too critical to me.  https://github.com/bahmutov/cypress-split/issues/121

2023-10-12 19:58 UTC, max-nextcloud approved these changes

2023-10-13 11:35 UTC, merged