feat: check and apply markdown for smart picker output
nextcloud/text pull request #5106
Opened 2023-12-08 15:07 UTC by luka-nextcloud

### 📝 Summary

* Resolves: #4784

Always consider smart picker output as markdown.

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

2023-12-21 21:34 UTC, juliushaertl commented on src/components/Suggestion/LinkPicker/suggestions.js
> +		/^#\s.*$/, // Headings: # text
Would be good to also cover headings of other levels h2-h6

2023-12-21 21:35 UTC, juliushaertl commented on src/components/Suggestion/LinkPicker/suggestions.js
> +		/- .*/, // Unordered list: - item
Markdown also supports `+` and `*` as list entries

2023-12-21 21:36 UTC, juliushaertl commented on src/components/Suggestion/LinkPicker/suggestions.js
> +		/\d\..*/, // Ordered list: 1. item
```suggestion
		/^\s\d\..*/m, // Ordered list: 1. item
```

2023-12-21 21:37 UTC, juliushaertl commented on src/components/Suggestion/LinkPicker/suggestions.js
> +		/^>\s.*/, // Blockquote: > text
```suggestion
		/^>+\s.*/, // Blockquote: > text
```

2023-12-21 21:37 UTC, juliushaertl commented on src/components/Suggestion/LinkPicker/suggestions.js
> +		/- .*/, // Unordered list: - item
```suggestion
		/^\s*[+-*]\s.*/m, // Unordered list: - item
```

2023-12-21 21:38 UTC, juliushaertl requested changes
A few suggestions for detecting the markdown syntax (I know we can't cover everything there), but otherwise this seems fine and works well 👍

2023-12-22 11:03 UTC, mejo- commented
Maybe I'm missing something here, but why do we have to detect markdown manually at all, instead of just doing `isValidMarkdown()` and always sending the content through `markdownit.render()` if that succeeds?

2023-12-22 13:12 UTC, juliushaertl commented
Hm,  unsure about that. It might be fine to just always pass it to markdown it indeed.

2023-12-22 14:18 UTC, luka-nextcloud commented
I have tried this way and faced an issue. The markdown-it render function always adds some newline character to content. So, If input value is an url, the inserted content will be a normal string instead of a link (enclose it in an angle brackets).

2023-12-28 09:56 UTC, juliushaertl approved these changes

2023-12-28 09:56 UTC, merged