remove old link when editing
nextcloud/text pull request #5690
Opened 2024-04-15 13:11 UTC by grnd-alt

2024-04-17 09:01 UTC, max-nextcloud commented
The current change works well when only changing a single link in a paragraph.
There are two more scenarios that would be good to account for:

## Link in a paragraph

Find more information on https://nextcloud.com as usual.

-> should only change the link.

## Link with custom text

[More informarion](https://nextcloud.com)

-> should only change the href.

2025-02-03 14:58 UTC, max-nextcloud requested changes
As I said earlier... this will not work if the link is not the only thing in a paragraph.

@grnd-alt would you be up for picking this up again?

2025-02-12 18:57 UTC, max-nextcloud reviewed
Looks good. Just one small remark about the test code.

2025-02-12 18:57 UTC, max-nextcloud commented on src/tests/marks/Link.spec.js
> +	})
This test doesn't really do what the title says.
The editor joins the two `<a>` tags because they have the same attrs. Then it replaces both of them.

I'd propose to use to different hrefs and test for only one of the links being replaced.

2025-03-07 13:14 UTC, juliusknorr commented
> Warning: Failed to restore: getCacheEntry failed: Cache service responded with 500

Looked odd, restarted cypress

2025-03-19 07:07 UTC, max-nextcloud reviewed
Just a minor comment. Other than that seems good code wise. Have not tested it though.

2025-03-19 07:07 UTC, max-nextcloud commented on src/tests/marks/Link.spec.js
> +	})
This test seems incomplete. It does not change anything but just asserts the initial state.

2025-03-19 13:15 UTC, max-nextcloud commented
Failing psalm test is unrelated. I'd be okay with force merging.

2025-03-20 07:57 UTC, merged