fix: ctrl+backspace in list item on firefox
nextcloud/text pull request #5962
Opened 2024-06-27 16:58 UTC by luka-nextcloud

### 📝 Summary

* Resolves: #5839

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

2024-06-27 18:53 UTC, juliushaertl requested changes

2024-06-27 18:53 UTC, juliushaertl commented on src/nodes/Paragraph.js
> +				if (window.triggeredModBackspace) {
This seems more like a dirty hack, could we rather please try to figure out the root cause? If it is not a problem in tiptap, there must be some difference in why our editor triggers a new line.

2024-06-28 12:29 UTC, juliushaertl commented
Thanks for checking that.

Let me put some references here as well:
https://github.com/ProseMirror/prosemirror-view/blob/master/CHANGELOG.md#1337-2024-05-31
https://github.com/ProseMirror/prosemirror-view/commit/8c9a7d25021ce8e99d03a63c7fb7033a524fd4db

Was bumped in tiptap upstream for the upcoming 2.5.0 release with https://github.com/ueberdosis/tiptap/commit/747985b3a7617e35702a6dab4ecc87c76610204b

2024-06-28 12:30 UTC, juliushaertl commented
@luka-nextcloud @max-nextcloud Any oppinion on having direct prosemirror dependencies again in our package.json? I feel this could cause issues in the future if tiptap ships another version. Shall we just wait for the upstream update? Or merge and revert fixed in upstream?

2024-06-28 14:35 UTC, luka-nextcloud commented
I think if this issue is not urgent, we'd better wait for the new tiptap release.

2024-07-05 04:45 UTC, closed without merging

2024-07-05 04:45 UTC, juliushaertl commented
Left a comment about this in the issue