perf(rich_workspace): only add property for parent
nextcloud/text pull request #5963
Opened 2024-06-28 11:11 UTC by ShGKme

### 📝 Summary

Fixes a performance regression for instances with many external storages.

#### Steps to reproduce

1. Add 300-500 s3 external storages and mount to the root subfolder
2. Enable `text` app
3. See 10-15s loading time on `/apps/files/files` for PROPFIND request for local s3.
   With external s3, like Amazon, it could be 10 times slower.

That was a regression in 28.

| s3  | 28   | 27       |
|-----|------|----------|
| 0   | 0.1s | 0.1s     |
| 100 | 3s   | 0.2s     |
| 200 | 6s   | 0.5s     |
| 300 | 9s   | 0.9s     |
| 400 | 12s  | 1-2s     | 
| 500 | 15s  | 1.1-2.4s |

#### The problem

There is a new `<nc:rich_workspace>` property in each Node in the response. To add this property (even empty), `text` checks for a file in every child folder, which could be an external remote storage.

Having a hundred external storages mounted in one parent, it results in a hundred requests to remotes for the data that is not really required to have in advance.

### 🚧 TODO

- [x] Only add property for parent ignoring deep nodes as it was in the past

### 💥 Breaking changes

This breaks the Android Files client a bit—it uses a response from a parent to know about description in children.

Broken scenario:
1. Open root
2. Open a child without README
3. Go back to parent
4. Open a child with README
   - Before: README is shown as a description
   - After: README is not shown and a swipe-reload is required

### Alternative solution

Only ignore external storages, which has the most performance impact.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

2024-06-28 11:25 UTC, juliushaertl commented
So the test actually has a comment on this that proofs what we discussed in the call:

https://github.com/nextcloud/text/blob/3a9c4f6f7a0ce3e6d148314311730b35250e34fc/cypress/e2e/propfind.spec.js#L43-L56

@alperozturk96 Can you keep us posted here on if that is possible to address on Android?

2024-06-28 11:27 UTC, juliushaertl commented
Other failure is unrelated.

2024-07-02 08:20 UTC, juliushaertl commented
Discussed with @tobiasKaminsky  as we couldn't think of a proper way to make the root only result working with android:

- [ ] Check if we can just cache the existence of a rich workspace
- [ ] alternative would be to use a special property for web

2024-07-02 08:30 UTC, ShGKme commented
> * alternative would be to use a special property for web

Then performance regression is not fixed on Android, having ~10-100 times slower root update than it was in 27

2024-07-02 08:34 UTC, juliushaertl commented
> Then performance regression is not fixed on Android, having ~10-100 times slower root update than it was in 27

True, but this should already have been the case before 28. Though only considered as an alternative, caching is probably the most reasonable

2024-07-02 09:38 UTC, ShGKme commented
> True, but this should already have been the case before 28. Though only considered as an alternative, caching is probably the most reasonable

Why? It was added only in 28, or I got it wrong?

2024-07-02 09:41 UTC, juliushaertl commented
No, the clients already request this property since a long time. 28 only introduced a change where the web frontend now also fetches those, so the performance issue is also there earlier, just was never noticed.

2024-07-15 15:06 UTC, ShGKme commented
> * Check if we can just cache the existence of a rich workspace

Working on this solution

2025-02-07 10:20 UTC, juliusknorr commented
Initially added a commit here but split it now into https://github.com/nextcloud/text/pull/6891

2025-02-24 17:21 UTC, icewind1991 requested changes

2025-02-24 17:21 UTC, icewind1991 commented on lib/Service/WorkspaceService.php
> +				$exists = $folder->getStorage()->getCache('')->get($filename);
why the separate check here? if the file doesn't exist `get` throws a `NotFoundException` which is catched below.

Thus just duplicated the number of times we're querying the filecache

2025-04-09 20:19 UTC, juliusknorr commented on lib/Service/WorkspaceService.php
> +				$exists = $folder->getStorage()->getCache('')->get($filename);
The reason for this issue was slow performance with federated shares or external webdav storages where the additional check on the cache turned out faster then getting the file from the remote, but agree that we probably should not do that extra.

2025-04-09 20:55 UTC, juliusknorr commented
After this came up again as a performance bottleneck also for local folders, I pushed a change as an additional commit to introduce a separate property that only returns the workspace on the root node.

This is mainly to keep backward compatibility for the mobile clients that as far as I understood @tobiasKaminsky do not have a good way to work with only the parent workspace result. Performance wise the clients should also switch to the flat property at some point, so maybe you can check if that is still the case.

2025-04-09 20:57 UTC, juliusknorr commented
Blackfire proof of saving queries on a folder with 100 subfolders that have a readme of random casing each (Readme/README/readme)
<img width="1679" alt="Screenshot 2025-04-09 at 22 56 31" src="https://github.com/user-attachments/assets/f42c9ad7-d30a-4928-a640-9861c9a8d820" />

2025-04-10 05:38 UTC, tobiasKaminsky commented
@juliusknorr if there is no "regression", then client will work.
For future: to which property should the clients switch?

2025-04-10 09:25 UTC, juliusknorr commented
Can you test the clients with this specific commit https://github.com/nextcloud/text/pull/5963/commits/e5efd6477f689d69d4cdbb00d65c46af9dd3fe40 ? That would help to decide if we actually need the extra one.

I remember in the past the clients were confused when navigating around folders as the property was then intitially not reported on the child folders, only once you did a propfind directly to it.

2025-04-10 14:26 UTC, icewind1991 commented
failing cypress test seems related

2025-08-19 12:11 UTC, icewind1991 approved these changes

2025-08-19 14:32 UTC, icewind1991 commented
Can this be finished as it's preventing workspace from being enabled on c.nc.c

2025-09-04 08:49 UTC, max-nextcloud commented
> Can you test the clients with this specific commit [e5efd64](https://github.com/nextcloud/text/commit/e5efd6477f689d69d4cdbb00d65c46af9dd3fe40) ? That would help to decide if we actually need the extra one.

@tobiasKaminsky Could you test? (see https://github.com/nextcloud/text/pull/5963#issuecomment-2792124269)

2026-01-26 16:02 UTC, icewind1991 commented
This is still relevant

2026-06-24 13:16 UTC, max-nextcloud commented
#8497 superseeds this. Please reopen if i am mistaking there.

2026-06-24 13:16 UTC, closed without merging