fix(mention): No extra whitespace in markdown before/after mentions
nextcloud/text pull request #6315
Opened 2024-09-04 16:17 UTC by mejo-

Fixes: #6314

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests

2024-09-04 16:57 UTC, mejo- commented
/backport to stable30

2024-09-04 16:57 UTC, mejo- commented
/backport to stable29

2024-09-05 10:03 UTC, max-nextcloud requested changes
Fine with me... just needs to remove the `.only` in the tests to make sure the other tests still run.

2024-09-05 10:03 UTC, max-nextcloud commented on src/tests/markdown.spec.js
> +	test.only('mentions', () => {
```suggestion
	test('mentions', () => {
```

2024-09-05 10:03 UTC, max-nextcloud commented on src/tests/markdown.spec.js
> +	test.only('mentions', () => {
```suggestion
	test('mentions', () => {
```

2024-09-05 10:55 UTC, mejo- commented on src/tests/markdown.spec.js
> +	test.only('mentions', () => {
Good catch, fixed now.

2024-09-05 13:40 UTC, luka-nextcloud approved these changes

2024-09-05 13:58 UTC, merged