feat(menu): Put list items in submenu, add indention options
nextcloud/text pull request #6353
Opened 2024-09-13 12:04 UTC by mejo-

Fixes: #2438
Contributes to: #2836

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
![image](https://github.com/user-attachments/assets/5ca9ac32-adc3-4552-a3b1-0b675a1ff989) | ![image](https://github.com/user-attachments/assets/09a3ec0a-bbc3-41f0-9536-414b881a1d4e)

| Screencast |
| --- |
| ![recording1](https://github.com/user-attachments/assets/eff54eae-7baa-4168-9748-c5ec811f37c2) |

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests

2024-09-13 13:04 UTC, jancborchardt approved these changes
Very nice! Basically good to go, only 2 remarks:
- [x] A separator line between the list options and indentation options would be useful (as per the suggestion)

Sidenote: This change makes it more obvious that once you decide for ordered/unordered list or checklist, you can not change between them. Any specific reason for that? (But that's a different issue.

2024-09-13 13:05 UTC, jancborchardt requested changes
Sorry, actually missed something: It is "indent**ation**", not "indention". :)

2024-09-13 13:21 UTC, juliushaertl commented on cypress/e2e/workspace.spec.js
> +	it.only('creates lists', function() {
```suggestion
	it('creates lists', function() {
```

2024-09-14 06:16 UTC, mejo- commented
> Sidenote: This change makes it more obvious that once you decide for ordered/unordered list or checklist, you can not change between them. Any specific reason for that? (But that's a different issue.

True, but that's another issue tracked in its own issue already. No idea so far, why this is the case.

2024-09-14 06:32 UTC, mejo- commented
> - A separator line between the list options and indentation options would be useful (as per the suggestion)
> - (EDIT: Actually both seem to exist, but "indentation" is the more commonly used one. If we want to be short, then we can use "Increase indent" / "Decrease indent".)

Thanks for the review @jancborchardt. Both added now, see the updated screenshot (I didn't update the screencast) :blush:

2024-09-16 14:12 UTC, juliushaertl approved these changes

2024-09-16 18:07 UTC, merged

2024-09-20 15:37 UTC, mejo- commented
/backport to stable30