feat(attachments): add support for creating new attachments
nextcloud/text pull request #6676
Opened 2024-11-21 14:03 UTC by pbirrer

These changes enable users to create and insert new attachment files directly from within the editor.

### 📝 Summary

- Introduced a new endpoint (`Attachment#createAttachment`) to create attachment files via POST requests.
- Added `createAttachment` method in `AttachmentService` to handle file creation logic with permission checks.
- Updated `MediaHandler.vue` and `MediaHandler.provider.js` to integrate the new attachment creation functionality in the editor.
- Enhanced `ActionAttachmentUpload.vue` to support dynamic attachment creation from file app templates.
- Extended `SessionApi.js` with a `createAttachment` method to interface with the new API endpoint.

#### 🖼️ Screenshots

![text-create-attachment](https://github.com/user-attachments/assets/795e054f-99c7-4320-a45c-a2de95f2db9f)

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

2024-12-03 13:44 UTC, max-nextcloud commented
Dear @pbirrer 

At first sight this looks like a good addition to me. I wonder if it becomes very verbose if one has a lot of possible file types that can be created.

@marcoambrosini What do you think from a design perspective?

2024-12-04 09:32 UTC, marcoambrosini commented
I agree that this is a great addition too, should we have too many "New" menu items, we can add a "Create new" submenu in the future

2024-12-04 10:19 UTC, pbirrer commented
Yeah, a 'Create New' submenu could also work pretty well here. The number of file types you can create depends on what’s registered in the files app—it adjusts based on the apps being used in your Nextcloud instance.

2024-12-17 10:10 UTC, max-nextcloud requested changes
I tested it locally and noticed that creating the new files is inconsistent with how attachments are inserted thus far.

I'll attach a screencast to illustrate what i mean by that.

If I upload a `.md` file from my computer it will show as a tiny preview with the filename and size. Same if I insert it from the files already on the Nextcloud.

However if i use the new `Create new text file` functionality the file will be embedded.

The markdown syntax matches this difference (first file was uploaded, second was created):

```md
![New text file.md](.attachments.2371/New%20text%20file.md)

[http://nextcloud.local/index.php/f/2393](http://nextcloud.local/index.php/f/2393 (preview))
```

I understand you actually want the embedding, not just an attachment. From my point of view these are two different steps:
1. Enable the creation of new files as attachments (this PR)
2. Make attachments behave (more) like previews.

Please change the behavior to match the one of other attachments for now so we can get this in. I'll add a (failing) cypress test case in the attachments test suite that should pass once the created text files behave the same as the uploaded ones.

2024-12-17 10:11 UTC, max-nextcloud commented
Here's a [screencast](https://github.com/user-attachments/assets/672dfcb3-24ed-4760-9694-bf10f5e51f67) illustrating what I am referring to.

2024-12-17 20:11 UTC, rvjr commented
Hi @max-nextcloud,

you mean you want the link to use the syntax with the global file id, instead of the relative path? Or do you mean that the file shouldn't be previewed initially (which would not make much sense, when inserting new files...)?

2024-12-18 09:34 UTC, pbirrer commented
I understand that the inconsistency between the attachment options is unfortunate. However, as it stands, there’s no way to interact with the default view created by “Upload from computer” or “Insert from file” beyond directly downloading the file or deleting the entry. 

![attachment](https://github.com/user-attachments/assets/47482361-63d1-43c2-89dc-ac771b395c0a)

But I’m assuming this isn’t the intended behavior, correct?

2024-12-18 14:39 UTC, max-nextcloud commented
Thanks @rvjr and @pbirrer  for getting back so swiftly!

Let me try and answer you both at once...

> you mean you want the link to use the syntax with the global file id, instead of the relative path? Or do you mean that the file shouldn't be previewed initially (which would not make much sense, when inserting new files...)?

Yes... both was my thinking - but I see how an empty attachment that cannot even be accessed makes little sense.

> But I’m assuming this isn’t the intended behavior, correct?
Well - it's not what we want in the long run - but it's the current behavior of attachments.

I'd like to see a way to convert between the three:
* plain link
* small preview that opens in new tab / downloads
* embedded content that can be edited.
I think this is out of scope for this PR.

I'd be fine with what @pbirrer currently developed if we make sure...
* [ ] the [attachment cleanup](https://github.com/nextcloud/text/blob/main/lib/Service/AttachmentService.php#L544) does not wipe the files because it thinks the attachments were removed from the text content.
* [ ] tests ensure we don't accidentally break it.
* [ ] maybe the attachments section and the embedding new content section are visually separated in the menu.

2025-01-16 15:16 UTC, pbirrer commented
Hey @max-nextcloud,

I just added a separator bar in the dropdown menu to clearly separate the new entries from the old ones.

I also attempted to update the attachment cleanup routine. However, I wasn’t able to get the previews working with filenames in the URL, so now the cleanup function will look for any references by file ID as well.

Hope this helps! Let me know if you have any questions or feedback.

2025-01-29 11:29 UTC, max-nextcloud reviewed
Code looks good. I will test it one more time and hope we can merge ahead then.

2025-01-29 11:29 UTC, max-nextcloud commented on lib/Service/AttachmentService.php
> +			'/\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[\])*\])*\])*\])*\])*\])*\]\(\S+\/f\/(\d+)(?: \(preview\))?\)/',
We could be more permissive about the `(preview)` I think as markdown interprets this as the link title. On the other hand attachment handling usually applies to files attached via the text UI - so we can assume the links are formatted consistently.

2025-01-31 09:04 UTC, pbirrer commented on lib/Service/AttachmentService.php
> +			'/\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[\])*\])*\])*\])*\])*\])*\]\(\S+\/f\/(\d+)(?: \(preview\))?\)/',
How permissive would you like it to be? just ignoring any whitespace?

2025-02-01 15:48 UTC, rvjr commented on lib/Service/AttachmentService.php
> +			'/\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[(?>[^\[\]]+|\[\])*\])*\])*\])*\])*\])*\]\(\S+\/f\/(\d+)(?: \(preview\))?\)/',
maybe just ignore anything after `file_id`? Because when it matched, we have everything we need to know which file is being used.

2025-02-12 21:48 UTC, max-nextcloud approved these changes
Looks good now. Thanks a lot for following up here!

2025-02-12 22:26 UTC, max-nextcloud commented on cypress/e2e/attachments.spec.js
> +				return waitForRequestAndCheckAttachment(requestAlias, undefined, false)
This is failing on CI right now. I suspect the dom structure of the text attachment is different from the image dom structure.

2025-02-24 10:22 UTC, pbirrer commented on cypress/e2e/attachments.spec.js
> +				return waitForRequestAndCheckAttachment(requestAlias, undefined, false)
@max-nextcloud: Would you mind helping me with this issue? Most of the Cypress tests on my system are failing, and I currently don't have enough time to investigate this further.

2025-04-17 07:53 UTC, pbirrer commented
@max-nextcloud Do you have any suggestions on the next steps to help get this finally merged?

2025-05-01 08:53 UTC, merged

2025-05-01 08:55 UTC, max-nextcloud commented
> @max-nextcloud Do you have any suggestions on the next steps to help get this finally merged?

I'm sorry for taking so long to click the merge button :wink: - had a last quick review.

:bouquet: Thanks a lot for following up on this, adding and fixing the tests.